import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/context/ThemeContext";
import TanstackQueryProvider from "@/components/partials/TanstackQueryProvider";
import { UserProvider } from "@/context/AuthContext";

const geistSans = localFont({
  src: "./fonts/Yekan.woff",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Yekan.woff",
  weight: "100 900",
});


export const metadata = {
  title: "آرایشگاه کاخ اصلاح",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <UserProvider>
        <TanstackQueryProvider>
          <ThemeProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased font-custom`}
            >
              {children}
            </body>
          </ThemeProvider>
        </TanstackQueryProvider>
      </UserProvider>
    </html>
  );
}
